# Figure 5 — publication rendering, generated by scripts/31_figure5_structural.py
# Run:  pymol -cq FIG5_pymol.pml     (structures are fetched from the PDB)
set ray_opaque_background, 0
bg_color white
set cartoon_transparency, 0.1

# ---- C1  4EXK chain A  MBP  FUSION_INTRINSIC_CAVITY
fetch 4EXK, async=0
hide everything, 4EXK
create C1_chain, 4EXK and chain A and polymer
show cartoon, C1_chain
color skyblue, C1_chain
# NOTE: selections below use ENTITY (label_seq) ranges from SIFTS; map to auth
#       numbering with the manifest before use if they differ for 4EXK.
select C1_pocket, C1_chain and resi 111+12+14+15+150+153+154+155+156+210+230+330+337+340+341+344+41+42+44+45+61+62+63+65+66
color firebrick, C1_pocket
show sticks, C1_pocket
select C1_lig, 4EXK and not polymer and not solvent within 5 of C1_pocket
show spheres, C1_lig
color orange, C1_lig

# ---- C2  6ZX9 chain C  T4L  FUSION_INTRINSIC_CAVITY
fetch 6ZX9, async=0
hide everything, 6ZX9
create C2_chain, 6ZX9 and chain C and polymer
show cartoon, C2_chain
color skyblue, C2_chain
# NOTE: selections below use ENTITY (label_seq) ranges from SIFTS; map to auth
#       numbering with the manifest before use if they differ for 6ZX9.
select C2_pocket, C2_chain and resi 0
color firebrick, C2_pocket
show sticks, C2_pocket
select C2_lig, 6ZX9 and not polymer and not solvent within 5 of C2_pocket
show spheres, C2_lig
color orange, C2_lig

# ---- C3  6M97 chain A  BRIL  FUSION_INTRINSIC_CAVITY
fetch 6M97, async=0
hide everything, 6M97
create C3_chain, 6M97 and chain A and polymer
show cartoon, C3_chain
color skyblue, C3_chain
# NOTE: selections below use ENTITY (label_seq) ranges from SIFTS; map to auth
#       numbering with the manifest before use if they differ for 6M97.
select C3_pocket, C3_chain and resi 1003+1007+1040+1061+1102+1105+121+124
color firebrick, C3_pocket
show sticks, C3_pocket
select C3_lig, 6M97 and not polymer and not solvent within 5 of C3_pocket
show spheres, C3_lig
color orange, C3_lig

# ---- C4  4EPI chain A  T4L  TARGET_FUSION_INTERFACE
fetch 4EPI, async=0
hide everything, 4EPI
create C4_chain, 4EPI and chain A and polymer
show cartoon, C4_chain
color skyblue, C4_chain
# NOTE: selections below use ENTITY (label_seq) ranges from SIFTS; map to auth
#       numbering with the manifest before use if they differ for 4EPI.
select C4_pocket, C4_chain and resi 116+118+121+161+164+165+167+168+237+240+244+253+258+261+265+90
color firebrick, C4_pocket
show sticks, C4_pocket
select C4_lig, 4EPI and not polymer and not solvent within 5 of C4_pocket
show spheres, C4_lig
color orange, C4_lig

orient
set ray_trace_mode, 1
# ray 2400, 1800
# png FIG5_pymol.png, dpi=400
